# Generated by Django 3.1.2 on 2020-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_hod',
        ),
        migrations.AddField(
            model_name='user',
            name='is_lecturer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
