# Generated by Django 3.1.2 on 2020-11-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201031_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_hod',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_lecturer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
