# Generated by Django 3.1.2 on 2020-10-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20201028_1016'),
        ('examinations', '0002_auto_20201028_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='date_finished',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='examination',
            old_name='date_started',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='examination',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programtype'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.semester'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.session'),
        ),
    ]
