# Generated by Django 3.1.2 on 2020-11-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201104_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturercourseassignment',
            name='is_joined',
            field=models.BooleanField(default=False),
        ),
    ]
