# Generated by Django 3.1.2 on 2020-11-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_programtype_number_of_semester'),
        ('option', '0003_option_abbreviated_name'),
        ('department', '0007_auto_20201104_0822'),
        ('course', '0003_auto_20201104_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.option')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programtype')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.semester')),
            ],
        ),
    ]
