# Generated by Django 3.1.2 on 2020-10-27 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('course', '0003_auto_20201025_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.level'),
        ),
    ]
