# Generated by Django 3.1.2 on 2020-11-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursedistribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedistribution',
            name='program_type',
        ),
    ]
