# Generated by Django 3.1.2 on 2020-10-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_auto_20201025_1143'),
        ('student', '0008_student_is_course_ref'),
        ('lecturer', '0007_auto_20201026_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_registered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Fresh Course'), ('2', 'Carry over'), ('3', 'Spill over')], default='1', max_length=20, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerCourseAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_assigned', models.DateTimeField(auto_now_add=True)),
                ('is_joined', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.lecturer')),
            ],
        ),
    ]
