# Generated by Django 3.1.2 on 2020-10-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourseregistration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourseregistration',
            name='student',
        ),
        migrations.DeleteModel(
            name='LecturerCourseAssignment',
        ),
        migrations.DeleteModel(
            name='StudentCourseRegistration',
        ),
    ]
