# Generated by Django 3.1.2 on 2020-10-26 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(max_length=200, null=True)),
                ('date_time_sent', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=True)),
                ('target_receiver', models.CharField(choices=[('1', 'All'), ('2', 'Student only'), ('3', 'Staffs only'), ('4', 'Lecturers only'), ('5', 'Lecturers and Teachers only'), ('6', 'HODs only')], max_length=30, null=True)),
                ('degree', models.CharField(choices=[('1', 'Warning'), ('2', 'Info'), ('3', 'Danger'), ('4', 'Hint/Advice')], default='2', max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
