# Generated by Django 3.1.2 on 2020-11-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20201105_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivercategory',
            name='abbreviated_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
