# Generated by Django 3.1.2 on 2020-10-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('ND', 'National Diploma'), ('HND', 'Higher National Diploma'), ('GW', 'General Welding')])),
                ('duration', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
