# Generated by Django 3.1.2 on 2020-10-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20201027_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_month', models.CharField(max_length=10, null=True)),
                ('end_month', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('start_year', models.CharField(choices=[(2020, 2020)], max_length=5, null=True)),
                ('end_year', models.CharField(choices=[(2020, 2020)], max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programtype'),
        ),
    ]
