# Generated by Django 3.1.2 on 2020-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_auto_20201028_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtype',
            name='number_of_semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=4),
        ),
    ]
