# Generated by Django 3.1.2 on 2020-11-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_programtype_number_of_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.AddField(
            model_name='programtype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='programtype',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
