# Generated by Django 3.1.2 on 2020-11-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20201106_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtype',
            name='duration',
            field=models.IntegerField(default=0, help_text='in months'),
        ),
    ]
