# Generated by Django 3.1.2 on 2020-11-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='abbreviated_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
