# Generated by Django 3.1.2 on 2020-10-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20201024_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='activity_type',
            field=models.CharField(choices=[('1', 'academic'), ('2', 'non-academic')], default='academic', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='office',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
