# Generated by Django 3.1.2 on 2020-11-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_department_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.FileField(null=True, upload_to='images/department'),
        ),
    ]
