# Generated by Django 3.1.2 on 2020-10-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='office',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.CharField(choices=[('EED', 'Electrical and Electronics Engineering'), ('MED', 'Mechanical Engineering Department'), ('ISET', 'Industrial Safety and Environmental Technology'), ('GS', 'General Studies'), ('PMBS', 'Petroleum Marketting and Bussiness Studies'), ('WEOT', 'Welding Engineering and Offshore Technology'), ('PNGPD', 'Petroleum and Natural Gas Processing'), ('PEG', 'Petroleum and Geo-sciences')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
    ]
