# Generated by Django 3.1.2 on 2020-11-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_remove_lecturer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='photo',
            field=models.FileField(default=None, null=True, upload_to='images/lecturers'),
        ),
    ]
