# Generated by Django 3.1.2 on 2020-10-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_auto_20201021_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
