# Generated by Django 3.1.2 on 2020-11-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_lecturer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
