# Generated by Django 3.1.2 on 2020-11-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0004_auto_20201104_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='photo',
            field=models.FileField(null=True, upload_to='images/lecturers'),
        ),
    ]
