# Generated by Django 3.1.2 on 2020-10-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0005_remove_lecturer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='photo',
            field=models.FileField(null=True, upload_to='media/images'),
        ),
    ]
