# Generated by Django 3.1.2 on 2020-10-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0006_lecturer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_hod',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='photo',
            field=models.FileField(default=None, null=True, upload_to='media/images'),
        ),
    ]
