# Generated by Django 3.1.2 on 2020-10-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matriculation_no',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
