# Generated by Django 3.1.2 on 2020-10-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_matriculation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.TextField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
