# Generated by Django 3.1.2 on 2020-10-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201021_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
