# Generated by Django 3.1.2 on 2020-10-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('EED', 'Electrical and Electronics Engineering'), ('MED', 'Mechanical Engineering Department'), ('ISET', 'Industrial Safety and Environmental Technology'), ('GS', 'General Studies'), ('PMBS', 'Petroleum Marketting and Bussiness Studies'), ('WEOT', 'Welding Engineering and Offshore Technology'), ('PNGPD', 'Petroleum and Natural Gas Processing'), ('PEG', 'Petroleum and Geo-sciences')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='matriculation_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='option',
            field=models.CharField(choices=[('p&m', 'Power and Machine'), ('e&t', 'Electronics and Telecommunications'), ('i&c', 'Instrumentation and Control'), ('pp', 'Power Plant'), ('m', 'Manufacturing'), ('mre', 'Mineral Resources')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('ND', 'National Diploma'), ('HND', 'Higher National Diploma'), ('GW', 'General Welding')], max_length=50, null=True),
        ),
    ]
