# Generated by Django 3.1.2 on 2020-10-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('1', 'Full-Time'), ('2', 'Part-Time')], max_length=15, null=True),
        ),
    ]
