# Generated by Django 3.1.2 on 2020-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20201020_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
