# Generated by Django 3.1.2 on 2020-10-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_department_abbreviated_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.FileField(null=True, upload_to='media/images/department'),
        ),
    ]
