# Generated by Django 3.1.2 on 2020-10-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0002_program_program_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('session', models.CharField(choices=[('1', '2020/2021'), ('2', '2021/2022'), ('3', '2022/2023')], max_length=9)),
                ('semester', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], max_length=30, null=True)),
                ('program_type', models.CharField(choices=[('1', 'Full-Time'), ('2', 'Part-Time')], max_length=20, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
